import { DistrictInfo, MemoryItem, CityAnnouncement } from './types';

export const DISTRICTS: Record<string, DistrictInfo> = {
  central: {
    id: 'central',
    name: 'CENTRAL DISTRICT',
    tagline: 'LAPD Monoliths & Wallace Spires',
    description: 'Corporate monoliths pierce low rain clouds. A 30-meter holographic Joi projection towers above wet asphalt. Flying Spinners slice through the mist along illuminated skyways.',
    center: [0, 0, 0],
    bounds: { minX: -25, maxX: 35, minZ: -25, maxZ: 35 },
    ambientColor: '#38bdf8',
    fogDensity: 0.0085,
  },
  old_quarter: {
    id: 'old_quarter',
    name: 'OLD QUARTER',
    tagline: 'White Dragon Noodles & Neon Alleys',
    description: 'Narrow brick alleyways with White Dragon noodle bars, glowing paper lanterns, and synthetic memory dens beneath rain-drenched magenta and amber katakana signage.',
    center: [-55, 0, 15],
    bounds: { minX: -80, maxX: -25, minZ: -15, maxZ: 45 },
    ambientColor: '#f43f5e',
    fogDensity: 0.009,
  },
  metro: {
    id: 'metro',
    name: 'METRO DISTRICT',
    tagline: 'Off-World Transit Hub',
    description: 'Massive automated maglev terminal. High-speed magnetic express trains arrive beneath glowing violet canopies. Departure boards blink with off-world colony routes.',
    center: [-20, 0, -55],
    bounds: { minX: -55, maxX: 15, minZ: -85, maxZ: -25 },
    ambientColor: '#a855f7',
    fogDensity: 0.0085,
  },
  residential: {
    id: 'residential',
    name: 'RESIDENTIAL DISTRICT',
    tagline: 'Esperanza Tenement Blocks',
    description: 'High-density brutalist apartment blocks towering into the clouds. Glowing amber windows warm the cold drizzle. Flickering CRT televisions hum in quiet rooms.',
    center: [45, 0, -45],
    bounds: { minX: 15, maxX: 80, minZ: -80, maxZ: -15 },
    ambientColor: '#fbbf24',
    fogDensity: 0.0085,
  },
  industrial: {
    id: 'industrial',
    name: 'INDUSTRIAL DISTRICT',
    tagline: 'Wallace Protein & Power Relays',
    description: 'Colossal cooling towers with glowing hazard orange warning rings. High-pressure steam vents hiss into the wet air as automated power grids hum in perpetuity.',
    center: [65, 0, 30],
    bounds: { minX: 35, maxX: 95, minZ: 5, maxZ: 70 },
    ambientColor: '#f97316',
    fogDensity: 0.009,
  },
  waterfront: {
    id: 'waterfront',
    name: 'WATERFRONT',
    tagline: 'The Los Angeles Sea Wall',
    description: 'A colossal concrete barrier holding back the roaring black sea. Rain pounds the wet boardwalk while sweeping lighthouse searchlight beams scan the mist.',
    center: [-50, 0, 70],
    bounds: { minX: -85, maxX: -15, minZ: 45, maxZ: 95 },
    ambientColor: '#06b6d4',
    fogDensity: 0.008,
  },
  rooftop: {
    id: 'rooftop',
    name: 'ROOFTOP GARDENS',
    tagline: 'Sanctuary Above the Smog',
    description: 'A glass-domed botanical spire high above the city at elevation 32m. Rain drums gently on the skylight looking down upon the endless sea of neon towers.',
    center: [0, 32, 0],
    bounds: { minX: -20, maxX: 20, minZ: -20, maxZ: 20 },
    ambientColor: '#10b981',
    fogDensity: 0.007,
  },
};

export const INITIAL_MEMORIES: MemoryItem[] = [
  {
    id: 'mem_coffee',
    memoryCode: 'MEMORY 001',
    title: 'THE WARM PORCELAIN',
    objectType: 'coffee',
    district: 'central',
    districtName: 'Central District',
    locationSpecific: 'Nexus Promenade // Cafe Kiosk 03',
    timestamp: '21:39:14',
    position: [6, 1.1, 4],
    objectName: 'Black Ceramic Mug',
    shortContext: 'Left sitting on a wet metal cafe table beneath an awning.',
    evidenceText: [
      'The surface of the coffee has accumulated ripples from dripping rainwater.',
      'A faint wisp of condensation clings to the ceramic handle.',
      'A receipt pinned beneath the saucer reads: "ORDER #402 — TABLE 4 — TIME 21:38".',
      'Whoever purchased this did not have time to take a single sip.'
    ],
    visualPrompt: 'A steaming dark mug on wet brushed steel, raindrops reflecting neon cyan advertisements.',
    discovered: false,
  },
  {
    id: 'mem_watch',
    memoryCode: 'MEMORY 002',
    title: 'THE FROZEN SECONDS',
    objectType: 'watch',
    district: 'metro',
    districtName: 'Metro District',
    locationSpecific: 'Platform 4 Eastbound // Bench 02',
    timestamp: '21:47:12',
    position: [-18, 1.1, -48],
    objectName: 'Mechanical Chronometer',
    shortContext: 'Found on an acrylic waiting bench beside an automated train platform.',
    evidenceText: [
      'The crystal face is completely intact, free of any scratches or impact marks.',
      'The internal mechanical gear is oscillating rapidly back and forth in place without advancing.',
      'The hands remain stuck at precisely 21:47:12.',
      'Engraved on the underside casing: "For Marcus. Time is the only thing we truly share."'
    ],
    visualPrompt: 'A brass pocket watch on cold wet concrete, second hand vibrating in perpetual lockstep.',
    discovered: false,
  },
  {
    id: 'mem_drawing',
    memoryCode: 'MEMORY 003',
    title: 'THE BLUE CIRCLE',
    objectType: 'drawing',
    district: 'residential',
    districtName: 'Residential District',
    locationSpecific: 'Tower 08 // Ground Residence Terrace',
    timestamp: '18:42:00',
    position: [42, 1.2, -42],
    objectName: "Child's Crayon Drawing",
    shortContext: 'Taped to an outdoor refrigerator panel under a concrete overhang.',
    evidenceText: [
      'Drawn on coarse gray construction paper with primary color wax crayons.',
      'Shows three stick figures holding hands at the base of a gigantic residential tower.',
      'Where the gray clouds should part, a colossal indigo-blue ring fills the entire upper sky.',
      'Carefully lettered in purple crayon at the bottom: "The sky opened its eye. We are going inside tonight."'
    ],
    visualPrompt: 'A childlike drawing showing a huge radiant sapphire sphere hovering over skyscrapers.',
    discovered: false,
  },
  {
    id: 'mem_tv',
    memoryCode: 'MEMORY 004',
    title: 'THE LOOPING CARRIER',
    objectType: 'tv',
    district: 'residential',
    districtName: 'Residential District',
    locationSpecific: 'Terrace Flat // Window Parlor',
    timestamp: '22:04:30',
    position: [48, 1.3, -36],
    objectName: 'Flickering CRT Monitor',
    shortContext: 'A heavy monitor broadcasting through a shattered street-level window.',
    evidenceText: [
      'Static scanlines wash across a high-contrast amber emergency display.',
      'Scroll text repeats: "VESPER CIVIL DEFENSE: POPULATION SYNCHRONIZATION EVENT COMPLETE."',
      'Secondary line: "ALL RESIDENTS HAVE COMPLIED WITH TRANSLATION PROTOCOL. REMAINING INFRASTRUCTURE REMAINS AUTONOMOUS."',
      'No emergency siren followed. Only a low, calm synthesized voice repeating: "Thank you for existing with us."'
    ],
    visualPrompt: 'Amber phosphor scanlines flickering through rain droplets on a dark windowpane.',
    discovered: false,
  },
  {
    id: 'mem_phone',
    memoryCode: 'MEMORY 005',
    title: 'THE UNSENT TRANSMISSION',
    objectType: 'phone',
    district: 'old_quarter',
    districtName: 'Old Quarter',
    locationSpecific: 'Alleyway 07 // Glass Tele-Booth',
    timestamp: '21:44:58',
    position: [-52, 1.2, 12],
    objectName: 'Encrypted Handheld Terminal',
    shortContext: 'Dangling from an elastic coiled cable inside an illuminated pay booth.',
    evidenceText: [
      'Display backlight flickers faintly in cyan and magenta neon light.',
      'An outgoing text draft is frozen on the screen, cursor blinking.',
      '"Kael, don\'t take the underground line. They told us it was a chemical spill, but that\'s not true."',
      '"I looked up from the roof. The clouds didn\'t rain water... they were raining silence. People are walking up into it. It isn\'t painful. I\'m leaving the keys here."'
    ],
    visualPrompt: 'A cracked holographic glass phone hanging in an illuminated phone booth amid dark rain.',
    discovered: false,
  },
  {
    id: 'mem_cake',
    memoryCode: 'MEMORY 006',
    title: 'THE NINTH BIRTHDAY',
    objectType: 'cake',
    district: 'old_quarter',
    districtName: 'Old Quarter',
    locationSpecific: 'Lantern Street // Pastry Counter',
    timestamp: '19:15:00',
    position: [-44, 1.1, 28],
    objectName: 'Iced Confection with Candles',
    shortContext: 'Sitting on a clean wooden display counter behind an unlocked sliding door.',
    evidenceText: [
      'Frosting decorated with miniature stars and piped silver lettering: "HAPPY 9TH BIRTHDAY MAYA".',
      'Nine slender striped candles remain untouched, their wicks clean and unlit.',
      'Paper party hats and folded napkins lie neatly arranged for seven guests.',
      'No signs of panic, struggle, or rushed departure. The door was left unlocked, the chime still ringing gently in the wind.'
    ],
    visualPrompt: 'A delicate pastel birthday cake under dim paper lantern light as rain drips outside the glass.',
    discovered: false,
  },
  {
    id: 'mem_ticket',
    memoryCode: 'MEMORY 007',
    title: 'THE ZERO TICKET',
    objectType: 'ticket',
    district: 'metro',
    districtName: 'Metro District',
    locationSpecific: 'Turnstile Bank C // Automated Validator',
    timestamp: '21:46:02',
    position: [-14, 1.2, -38],
    objectName: 'Magnetic Transit Card',
    shortContext: 'Still protruding from the card slot of an active holographic gate.',
    evidenceText: [
      'Card type: Standard Monthly Commuter Pass // ID: 884-9021-V.',
      'Origin: Central Station. Destination display: "[ STATION NULL // ELEVATION 40,000M ]".',
      'Fare deducted: 0.00 CREDITS.',
      'The green turnstile gate arm remains locked open, waiting for someone to step through.'
    ],
    visualPrompt: 'A glowing magnetic transit card stuck in a holographic turnstile gate in an empty station.',
    discovered: false,
  },
  {
    id: 'mem_umbrella',
    memoryCode: 'MEMORY 008',
    title: 'THE DRY SHOES',
    objectType: 'umbrella',
    district: 'waterfront',
    districtName: 'Waterfront District',
    locationSpecific: 'Pier 09 // Sea Wall Promenade',
    timestamp: '22:11:05',
    position: [-46, 1.1, 68],
    objectName: 'Translucent Polycarbonate Umbrella',
    shortContext: 'Lying open on a wet wooden bench facing out over the black bay.',
    evidenceText: [
      'Rain drums rhythmically against the clear canopy of the umbrella.',
      'Directly beneath the bench, perfectly sheltered and bone dry, sits a pair of neatly aligned leather dress shoes.',
      'The socks were left tucked inside the shoes.',
      'No footprints lead toward the railing. No ripples in the water below indicate anyone fell.'
    ],
    visualPrompt: 'A clear umbrella dripping rain on a dock bench with dry shoes beneath, overlooking a dark endless sea.',
    discovered: false,
  },
  {
    id: 'mem_terminal',
    memoryCode: 'MEMORY 009',
    title: 'THE ASCENSION LOG',
    objectType: 'terminal',
    district: 'rooftop',
    districtName: 'Rooftop Gardens',
    locationSpecific: 'Observatory Spire // Master Telemetry Console',
    timestamp: '22:15:00',
    position: [0, 33.2, 0],
    objectName: 'Directorate Observatory Terminal',
    shortContext: 'A glowing circular console pulsing with cyan data rings beneath the glass sky.',
    evidenceText: [
      'Telemetry Report: "Harmonic convergence achieved across all 7 metropolitan sectors at 21:45."',
      '"Total population transferred: 2,418,903 citizens. Structural integrity of physical city: 100%."',
      '"The physical vessel is preserved. The rain will wash the streets clean for as long as needed."',
      '"They did not die. They were not taken against their will. They simply stepped out of the rain."',
      'System status: "CITY AUTOMATION CYCLE: ETERNAL STANDBY. WAITING FOR RETURN."'
    ],
    visualPrompt: 'A crystalline holographic sphere revealing star charts and population frequency waves over the skyline.',
    discovered: false,
  },
];

export const CITY_ANNOUNCEMENTS: CityAnnouncement[] = [
  {
    id: 'ann_1',
    time: '21:50',
    source: 'LAPD SPINNER DISPATCH',
    message: 'Notice: Skyway traffic corridor restricted to authorized patrol vehicles. High-altitude airspeed nominal.',
  },
  {
    id: 'ann_2',
    time: '22:05',
    source: 'WALLACE EARTH // SYNTHETICS',
    message: 'Everything you want to see. Everything you want to hear. The new Nexus integration cycle is operating at peak fidelity.',
  },
  {
    id: 'ann_3',
    time: '22:18',
    source: 'LOS ANGELES 2049 METEOROLOGY',
    message: 'Precipitation index: Constant drizzle. Cloud base: 45 meters. Sea wall surge barriers holding at 100% capacity.',
  },
  {
    id: 'ann_4',
    time: '22:32',
    source: 'VESPER MUNICIPAL SYNCHRONIZER',
    message: 'Reminder: Streetlights and automated power grids remain on perpetual cycle. You are never walking alone in the dark.',
  },
  {
    id: 'ann_5',
    time: '22:45',
    source: 'COMMUNICATION BEACON 01',
    message: 'To Officer KD6-3.7 or anyone listening... the doors were never locked. You are always welcome to step inside.',
  },
];

export const CHAPTERS = [
  {
    number: 1,
    title: 'THE CITY',
    description: 'The rain falls endlessly upon empty streets. The machinery runs on.',
  },
  {
    number: 2,
    title: 'THE ABSENCE',
    description: 'Signs of life remain everywhere, yet not a single soul can be found.',
  },
  {
    number: 3,
    title: 'THE SIGNAL',
    description: 'Automated municipal broadcasts begin glitching with strange frequencies.',
  },
  {
    number: 4,
    title: 'THE LAST DAY',
    description: 'The timeline of the final evening begins to piece together.',
  },
  {
    number: 5,
    title: 'AFTER RAIN',
    description: 'The truth revealed. The storm begins to clear.',
  },
];
